"""
docx_writer.py — Write a per-meeting Word document into the routed OneDrive
folder. Called by the meetings-digest skill at runtime.

Input: a JSON file describing the meeting + extracted items.
Output: one .docx file in {onedrive_base}/Plaud Meetings/{meeting_type}/[{week_folder}/]
        named '{prefix}.{short_title} ({attendees}).docx'

In v2.2.2+ meeting types with weekly_subfolders=true (default for any
type with include_in_weekly_rollup=true, i.e. Kingsway Pharma) get a
per-ISO-week subfolder inserted:

  OneDrive/Plaud Meetings/Kingsway Pharma/
    KPM.May 25-29, 2026 (Week 22)/
      KPM.Q3 Plans (John Smith).docx
      KPM.Pricing Pushback (Sarah Jones, Mark Lee).docx
      KPR.May 25-29, 2026 (Week 22).docx   ← weekly rollup lives here too

Types with weekly_subfolders=false (Church, Personal by default) stay
flat:

  OneDrive/Plaud Meetings/Personal/
    PM.Dentist Reminder.docx

The {prefix} comes from config.meeting_routing.types[].filename_prefix
(KPM / CHM / PM by default — the trailing M disambiguates meeting
files from other files the client might keep with the same 2-letter
prefix). {short_title} is the operator-meaningful 3-6 word summary of
the meeting's topic — generated by Claude during extraction, passed in
as `recording_title`. {attendees} is the comma-joined list of people
the operator met WITH (not including the operator).

Input JSON shape:
{
  "meeting_type": "Kingsway Pharma",         # routed folder
  "recording_title": "Q3 Plans",             # short 3-6 word topic summary
  "attendees": ["John Smith", "Sarah Jones"],# who the operator met with (not them)
  "recap": "2-3 sentence summary of the meeting (v2.2.4+)",   # rendered at top
  "recorded_at": "2026-05-22T14:30:00-04:00",
  "duration_minutes": 47.3,
  "speakers": ["Garrett", "John Smith"],     # voice-diarization, includes operator
  "source_file_id": "rec_abc123",
  "transcript_excerpt": "...first 500 chars...",   # used for the routing audit
  "action_items": [ {action, owner, due, priority, context, source_timestamp}, ... ],
  "decisions":   [ {what, why, source_timestamp}, ... ],
  "open_questions": [ {question, raised_by, source_timestamp}, ... ],
  "notable_quotes": [ {quote, speaker, source_timestamp}, ... ]
}

Filename collision policy: if the target filename already exists (same
prefix + title + attendees on a different day), the recorded date is
appended: 'KP.Q3 Plans (John Smith) - 2026-05-22.docx'. If THAT exists
too (two meetings same day with the same title + attendees), append the
HHMM as well: 'KP.Q3 Plans (John Smith) - 2026-05-22 1430.docx'.

Usage:
    python3 docx_writer.py --input /tmp/meeting.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

CONFIG_PATH = Path.home() / ".claude" / "skills" / "meetings-digest" / "config.json"

try:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
except ImportError:
    sys.stderr.write("ERROR: python-docx not installed. Run: python3 -m pip install python-docx\n")
    sys.exit(1)


# Brand colors — kept in sync with rollup_docx_writer.py
GALLANT_DEEP_NAVY = RGBColor(0x1A, 0x2A, 0x44)
GALLANT_GRAPHITE  = RGBColor(0x3D, 0x4A, 0x59)
GALLANT_MUTED     = RGBColor(0x6C, 0x75, 0x83)
GALLANT_DIVIDER   = RGBColor(0xCC, 0xCC, 0xCC)


def _set_run(run, *, bold=False, italic=False, size=11, color=None, font="Calibri") -> None:
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    run.font.name = font
    if color:
        run.font.color.rgb = color


def _section_header(doc, text: str) -> None:
    """ALL CAPS section header in deep navy with subtle bottom rule."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(18)
    p.paragraph_format.space_after = Pt(6)
    r = p.add_run(text.upper())
    _set_run(r, bold=True, size=12, color=GALLANT_DEEP_NAVY)
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "4")
    bottom.set(qn("w:color"), "CCCCCC")
    pBdr.append(bottom)
    pPr.append(pBdr)


def _body_run(p, text: str, *, bold=False, italic=False, color=None) -> None:
    r = p.add_run(text)
    _set_run(r, bold=bold, italic=italic, size=11, color=color or GALLANT_GRAPHITE)


def _detail_line(doc, parts: list[str], indent_in: float = 0.35) -> None:
    if not parts:
        return
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Inches(indent_in)
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(4)
    r = p.add_run("    ".join(parts))
    _set_run(r, italic=True, size=9, color=GALLANT_MUTED)


def load_config() -> dict[str, Any]:
    if not CONFIG_PATH.exists():
        sys.stderr.write(f"ERROR: config not found at {CONFIG_PATH}\n")
        sys.exit(1)
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def sanitize_filename(s: str, max_len: int = 80) -> str:
    """Make a string safe for Windows + Mac filesystems."""
    s = re.sub(r'[\\/:*?"<>|]', "", s)        # forbidden chars
    s = re.sub(r"\s+", " ", s).strip()        # collapse whitespace
    if len(s) > max_len:
        s = s[:max_len].rstrip()
    return s or "untitled"


def resolve_recording_datetime(recorded_at_iso: str | None) -> datetime:
    if not recorded_at_iso:
        return datetime.now()
    try:
        # tolerate trailing Z
        return datetime.fromisoformat(recorded_at_iso.replace("Z", "+00:00"))
    except ValueError:
        return datetime.now()


def _render_footer(doc, meeting: dict[str, Any]) -> None:
    """Standard footer: generation timestamp + source recording ID."""
    doc.add_paragraph()
    foot = doc.add_paragraph()
    fr = foot.add_run(
        f"Generated by Plaud Meetings Digest on {datetime.now().strftime('%Y-%m-%d %H:%M')}.    "
        f"Recording ID: {meeting.get('source_file_id', 'n/a')}"
    )
    _set_run(fr, italic=True, size=8, color=GALLANT_MUTED)


# Inline-markdown markers: **bold**, *italic*, `code`. Captures the marker
# so we can emit a styled run for the captured text and plain runs for the
# rest.
_MD_INLINE = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)")


def _render_inline_md(p, text: str) -> None:
    """Render a single line of inline markdown into the given paragraph,
    splitting on bold/italic/code markers. Plain spans get _body_run."""
    if not text:
        return
    parts = _MD_INLINE.split(text)
    for part in parts:
        if not part:
            continue
        if part.startswith("**") and part.endswith("**") and len(part) > 4:
            _body_run(p, part[2:-2], bold=True)
        elif part.startswith("*") and part.endswith("*") and len(part) > 2:
            _body_run(p, part[1:-1], italic=True)
        elif part.startswith("`") and part.endswith("`") and len(part) > 2:
            r = p.add_run(part[1:-1])
            _set_run(r, size=10, color=GALLANT_GRAPHITE, font="Consolas")
        else:
            _body_run(p, part)


def _render_markdown_body(doc, markdown: str) -> None:
    """
    Lightweight markdown-to-docx renderer for Plaud's get_note() output.
    Honors: # / ## / ### headings, - / * bullets, 1. numbered lists, >
    blockquotes, blank-line paragraph breaks, inline **bold** / *italic* /
    `code`. Anything more exotic (tables, images, links) falls through as
    plain paragraph text — Plaud's notes don't currently emit those.
    """
    lines = markdown.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    for raw in lines:
        line = raw.rstrip()
        if not line.strip():
            # Blank line: a small spacer paragraph
            sp = doc.add_paragraph()
            sp.paragraph_format.space_before = Pt(0)
            sp.paragraph_format.space_after = Pt(0)
            continue

        # Headings
        stripped = line.lstrip()
        if stripped.startswith("### "):
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(12)
            p.paragraph_format.space_after = Pt(4)
            r = p.add_run(stripped[4:].strip())
            _set_run(r, bold=True, size=11, color=GALLANT_DEEP_NAVY)
            continue
        if stripped.startswith("## "):
            _section_header(doc, stripped[3:].strip())
            continue
        if stripped.startswith("# "):
            _section_header(doc, stripped[2:].strip())
            continue

        # Bullet
        m_bullet = re.match(r"^(\s*)([-*])\s+(.*)$", line)
        if m_bullet:
            indent_spaces = len(m_bullet.group(1))
            body = m_bullet.group(3)
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.30 + 0.25 * (indent_spaces // 2))
            p.paragraph_format.space_before = Pt(2)
            p.paragraph_format.space_after = Pt(2)
            _body_run(p, "•  ", bold=True, color=GALLANT_DEEP_NAVY)
            _render_inline_md(p, body)
            continue

        # Numbered
        m_num = re.match(r"^(\s*)(\d+)\.\s+(.*)$", line)
        if m_num:
            indent_spaces = len(m_num.group(1))
            num = m_num.group(2)
            body = m_num.group(3)
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.30 + 0.25 * (indent_spaces // 2))
            p.paragraph_format.space_before = Pt(2)
            p.paragraph_format.space_after = Pt(2)
            _body_run(p, f"{num}.  ", bold=True, color=GALLANT_DEEP_NAVY)
            _render_inline_md(p, body)
            continue

        # Blockquote
        if stripped.startswith("> "):
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.45)
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(4)
            _render_inline_md(p, stripped[2:])
            continue

        # Plain paragraph
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(2)
        p.paragraph_format.space_after = Pt(2)
        _render_inline_md(p, line.strip())


def write_docx(meeting: dict[str, Any], output_path: Path) -> None:
    doc = Document()

    # Document-wide base font
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    recorded = resolve_recording_datetime(meeting.get("recorded_at"))
    duration = meeting.get("duration_minutes")
    speakers = meeting.get("speakers") or []
    attendees = meeting.get("attendees") or []
    mtype = meeting.get("meeting_type") or "Uncategorized"
    title = meeting.get("recording_title") or "Untitled Meeting"
    recap = meeting.get("recap")

    # ===== TITLE BLOCK ======================================================
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_after = Pt(2)
    t_run = title_p.add_run(f"{mtype.upper()} — {title.upper()}")
    _set_run(t_run, bold=True, size=20, color=GALLANT_DEEP_NAVY)

    if attendees:
        sub_p = doc.add_paragraph()
        sub_p.paragraph_format.space_after = Pt(2)
        s_run = sub_p.add_run(f"Meeting with {', '.join(attendees)}")
        _set_run(s_run, size=13, color=GALLANT_GRAPHITE)

    # Single meta line: Date | Duration | Speakers (if different from attendees)
    meta_p = doc.add_paragraph()
    meta_p.paragraph_format.space_after = Pt(6)
    meta_bits = [recorded.strftime("%A, %B %d, %Y at %-I:%M %p")]
    if duration:
        meta_bits.append(f"{int(duration)} minutes")
    meta_text = "    |    ".join(meta_bits)
    m_run = meta_p.add_run(meta_text)
    _set_run(m_run, size=10, color=GALLANT_MUTED, italic=True)

    # ===== PLAUD-NATIVE PASS-THROUGH (v2.3.0+) =============================
    # If the skill passed a `plaud_note_markdown` field, render it verbatim
    # below the title block and skip the structured sections entirely.
    # This honors Plaud's own summary structure (recap, key points, action
    # items, etc.) without Claude re-paraphrasing. The structured sections
    # below remain for backward compatibility (v2.2.x callers) and for the
    # weekly rollup which still synthesizes across meetings.
    plaud_note_markdown = meeting.get("plaud_note_markdown")
    if plaud_note_markdown:
        _render_markdown_body(doc, plaud_note_markdown)
        _render_footer(doc, meeting)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(str(output_path))
        return

    # ===== RECAP (when extracted) ==========================================
    if recap:
        _section_header(doc, "Recap")
        rp = doc.add_paragraph()
        rp.paragraph_format.space_before = Pt(4)
        rp.paragraph_format.space_after = Pt(4)
        _body_run(rp, recap)

    # ===== ACTION ITEMS ====================================================
    _section_header(doc, "Action Items")
    items = meeting.get("action_items") or []
    if items:
        for item in items:
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(2)
            # Clean [ ] checkbox (not Unicode ballot box) — universally
            # readable, prints cleanly, no emoji rendering inconsistency
            _body_run(p, "[ ]  ", bold=True, color=GALLANT_DEEP_NAVY)
            _body_run(p, item.get("action", "(no text)"), bold=True)
            details = []
            if item.get("owner"):
                details.append(f"Owner: {item['owner']}")
            if item.get("due"):
                details.append(f"Due: {item['due']}")
            if item.get("priority"):
                details.append(f"Priority: {item['priority']}")
            if item.get("context"):
                details.append(f"Context: {item['context']}")
            if item.get("source_timestamp"):
                details.append(f"At: {item['source_timestamp']}")
            _detail_line(doc, details, indent_in=0.45)
    else:
        p = doc.add_paragraph()
        _body_run(p, "No action items identified.", italic=True, color=GALLANT_MUTED)

    # ===== DECISIONS RECORDED ==============================================
    decisions = meeting.get("decisions") or []
    if decisions:
        _section_header(doc, "Decisions Recorded")
        for d in decisions:
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(2)
            _body_run(p, "•  ", bold=True, color=GALLANT_DEEP_NAVY)
            _body_run(p, d.get("what", "(no text)"), bold=True)
            if d.get("why"):
                rp = doc.add_paragraph()
                rp.paragraph_format.left_indent = Inches(0.35)
                rp.paragraph_format.space_before = Pt(0)
                rp.paragraph_format.space_after = Pt(2)
                _body_run(rp, "Rationale: ", bold=True)
                _body_run(rp, d["why"])
            if d.get("source_timestamp"):
                _detail_line(doc, [f"At: {d['source_timestamp']}"])

    # ===== OPEN QUESTIONS ==================================================
    questions = meeting.get("open_questions") or []
    if questions:
        _section_header(doc, "Open Questions")
        for q in questions:
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(2)
            _body_run(p, "•  ", bold=True, color=GALLANT_DEEP_NAVY)
            _body_run(p, q.get("question", "(no text)"), bold=True)
            details = []
            if q.get("raised_by"):
                details.append(f"Raised by: {q['raised_by']}")
            if q.get("source_timestamp"):
                details.append(f"At: {q['source_timestamp']}")
            _detail_line(doc, details)

    # ===== NOTABLE QUOTES ==================================================
    quotes = meeting.get("notable_quotes") or []
    if quotes:
        _section_header(doc, "Notable Quotes")
        for q in quotes:
            qp = doc.add_paragraph()
            qp.paragraph_format.space_before = Pt(6)
            qp.paragraph_format.space_after = Pt(2)
            qp.paragraph_format.left_indent = Inches(0.35)
            qr = qp.add_run(f"“{q.get('quote', '(no text)')}”")
            _set_run(qr, italic=True, size=11, color=GALLANT_GRAPHITE)
            attribution_bits = []
            if q.get("speaker"):
                attribution_bits.append(q["speaker"])
            if q.get("source_timestamp"):
                attribution_bits.append(f"at {q['source_timestamp']}")
            if attribution_bits:
                ap = doc.add_paragraph()
                ap.paragraph_format.left_indent = Inches(0.55)
                ap.paragraph_format.space_before = Pt(0)
                ap.paragraph_format.space_after = Pt(4)
                ar = ap.add_run(f"— {', '.join(attribution_bits)}")
                _set_run(ar, italic=True, size=9, color=GALLANT_MUTED)

    # ===== FOOTER ==========================================================
    doc.add_paragraph()
    foot = doc.add_paragraph()
    fr = foot.add_run(
        f"Generated by Plaud Meetings Digest on {datetime.now().strftime('%Y-%m-%d %H:%M')}.    "
        f"Recording ID: {meeting.get('source_file_id', 'n/a')}"
    )
    _set_run(fr, italic=True, size=8, color=GALLANT_MUTED)

    # ---- Save ----
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))


def resolve_routing_entry(meeting_type: str, config: dict[str, Any]) -> dict[str, Any]:
    """Return the matching meeting_routing.types entry for a meeting_type, or
    a synthetic fallback entry if it's the Uncategorized folder."""
    routing = config.get("meeting_routing", {})
    for entry in routing.get("types", []):
        if entry.get("folder") == meeting_type:
            return entry
    fallback_folder = routing.get("fallback_folder") or "Uncategorized"
    if meeting_type == fallback_folder:
        return {
            "folder": fallback_folder,
            "filename_prefix": routing.get("fallback_filename_prefix", "") or "",
            "rollup_filename_prefix": None,
            "weekly_subfolders": False,
            "include_in_weekly_rollup": False,
        }
    return {}


def week_folder_name(recorded: datetime, prefix: str) -> str:
    """
    Build a per-week subfolder name from a recording date.

    Format: '{prefix}.{Month} {start_day}-{end_day}, {year} (Week {iso_week})'
    Mon-Fri range labeling (workweek convention) — but the ISO week
    semantically covers Mon-Sun, so weekend recordings still bucket here.

    Examples:
      week_folder_name(2026-05-27, 'KPM') → 'KPM.May 25-29, 2026 (Week 22)'
      week_folder_name(2026-05-30, 'KPM') → 'KPM.May 25-29, 2026 (Week 22)'  (Sat → same bucket)
      week_folder_name(2026-06-01, 'KPM') → 'KPM.Jun 1-5, 2026 (Week 23)'
      week_folder_name(2026-05-29, 'KPM') with cross-month week:
        Mon May 25 - Fri May 29 → 'KPM.May 25-29, 2026 (Week 22)'
      A genuine cross-month week (e.g. recording on Mon Jun 1, week is May 28 to Jun 3):
        → 'KPM.Jun 1-5, 2026 (Week 23)'  (current week, no cross-month)
      For a week that genuinely spans months (e.g. Mon Mar 30 to Fri Apr 3):
        → 'KPM.Mar 30-Apr 3, 2026 (Week 14)'
    """
    iso_year, iso_week, iso_weekday = recorded.isocalendar()
    # iso_weekday: Mon=1, Sun=7
    monday = recorded - timedelta(days=iso_weekday - 1)
    friday = monday + timedelta(days=4)

    if monday.month == friday.month:
        date_range = f"{monday.strftime('%b')} {monday.day}-{friday.day}, {monday.year}"
    else:
        date_range = f"{monday.strftime('%b')} {monday.day}-{friday.strftime('%b')} {friday.day}, {monday.year}"

    if prefix:
        return f"{prefix}.{date_range} (Week {iso_week})"
    return f"{date_range} (Week {iso_week})"


def resolve_filename_prefix(meeting_type: str, config: dict[str, Any]) -> str:
    """
    Look up filename_prefix from config.meeting_routing.types matching the
    routed meeting_type. Falls back to fallback_filename_prefix (default "UN")
    for the Uncategorized folder. Returns empty string if config has no
    prefix info at all (defensive — older installs pre-v2.2.1 may not have
    the field; in that case fall back to the bare title).
    """
    routing = config.get("meeting_routing", {})
    for entry in routing.get("types", []):
        if entry.get("folder") == meeting_type:
            return entry.get("filename_prefix", "") or ""
    fallback_folder = routing.get("fallback_folder") or "Uncategorized"
    if meeting_type == fallback_folder:
        return routing.get("fallback_filename_prefix", "") or ""
    return ""


def resolve_output_path(meeting: dict[str, Any], base_dir: Path, config: dict[str, Any]) -> Path:
    """
    Compute the .docx output path under base_dir / 'Plaud Meetings' / <meeting_type>.

    Filename format (v2.2.1+): '{prefix}.{title} ({attendees}).docx'
      e.g. 'KP.Q3 Plans (John Smith, Sarah Jones).docx'

    Collision handling: if the target filename already exists, append the
    recorded date — and if THAT exists, append HHMM as well.
    """
    recorded = resolve_recording_datetime(meeting.get("recorded_at"))
    mtype = meeting.get("meeting_type") or "Uncategorized"
    title = meeting.get("recording_title") or "Untitled"
    attendees = meeting.get("attendees") or []
    entry = resolve_routing_entry(mtype, config)
    prefix = entry.get("filename_prefix", "") or ""
    weekly_subfolders = bool(entry.get("weekly_subfolders"))

    folder = base_dir / "Plaud Meetings" / sanitize_filename(mtype, 40)
    if weekly_subfolders:
        # Insert a per-week subfolder. Use the same prefix as the meeting
        # files (e.g. KPM) so a folder listing reads as a coherent set:
        #   KPM.May 25-29, 2026 (Week 22)/
        #     KPM.Q3 Plans (John Smith).docx
        folder = folder / sanitize_filename(week_folder_name(recorded, prefix), 90)

    # Build base filename: '{prefix}.{title}' or just '{title}' if no prefix
    title_part = sanitize_filename(title, 60)
    if prefix:
        base = f"{prefix}.{title_part}"
    else:
        base = title_part

    # Attendees: cap at 3 to keep filename under Windows 260-char path ceiling
    if attendees:
        attendee_strs = [sanitize_filename(a, 25) for a in attendees if a]
        attendee_strs = [a for a in attendee_strs if a]
        if len(attendee_strs) > 3:
            attendee_strs = attendee_strs[:3] + [f"+{len(attendees) - 3} more"]
        if attendee_strs:
            base = f"{base} ({', '.join(attendee_strs)})"

    candidate = folder / f"{base}.docx"
    if not candidate.exists():
        return candidate

    # Collision: append date
    date_part = recorded.strftime("%Y-%m-%d")
    candidate = folder / f"{base} - {date_part}.docx"
    if not candidate.exists():
        return candidate

    # Same-day collision: append HHMM too
    time_part = recorded.strftime("%Y-%m-%d %H%M")
    return folder / f"{base} - {time_part}.docx"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to JSON file with meeting data")
    parser.add_argument("--output", help="Explicit output path (overrides config-based routing)")
    args = parser.parse_args()

    config = load_config()
    base_dir_str = config.get("destination", {}).get("onedrive_folder")
    if not base_dir_str:
        sys.stderr.write("ERROR: destination.onedrive_folder not configured. Re-run install.\n")
        return 1

    base_dir = Path(base_dir_str).expanduser()
    if not base_dir.exists():
        sys.stderr.write(f"WARNING: OneDrive folder doesn't exist at {base_dir}; creating.\n")
        base_dir.mkdir(parents=True, exist_ok=True)

    in_path = Path(args.input)
    if not in_path.exists():
        sys.stderr.write(f"ERROR: input JSON missing: {in_path}\n")
        return 1
    meeting = json.loads(in_path.read_text(encoding="utf-8"))

    out_path = Path(args.output) if args.output else resolve_output_path(meeting, base_dir, config)
    write_docx(meeting, out_path)

    print(str(out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
