"""
docx_writer.py — Write a per-meeting Word document into the routed OneDrive
folder. Called by the meetings-digest skill at runtime.

Input: a JSON file describing the meeting + extracted items.
Output: one .docx file in {onedrive_base}/Plaud Meetings/{meeting_type}/[{week_folder}/]
        named '{prefix}.{short_title} ({attendees}).docx'

In v2.2.2+ meeting types with weekly_subfolders=true (default for any
type with include_in_weekly_rollup=true, i.e. Kingsway Pharma) get a
per-ISO-week subfolder inserted:

  OneDrive/Plaud Meetings/Kingsway Pharma/
    KPM.May 25-29, 2026 (Week 22)/
      KPM.Q3 Plans (John Smith).docx
      KPM.Pricing Pushback (Sarah Jones, Mark Lee).docx
      KPR.May 25-29, 2026 (Week 22).docx   ← weekly rollup lives here too

Types with weekly_subfolders=false (Church, Personal by default) stay
flat:

  OneDrive/Plaud Meetings/Personal/
    PM.Dentist Reminder.docx

The {prefix} comes from config.meeting_routing.types[].filename_prefix
(KPM / CHM / PM by default — the trailing M disambiguates meeting
files from other files the client might keep with the same 2-letter
prefix). {short_title} is the operator-meaningful 3-6 word summary of
the meeting's topic — generated by Claude during extraction, passed in
as `recording_title`. {attendees} is the comma-joined list of people
the operator met WITH (not including the operator).

Input JSON shape:
{
  "meeting_type": "Kingsway Pharma",         # routed folder
  "recording_title": "Q3 Plans",             # short 3-6 word topic summary
  "attendees": ["John Smith", "Sarah Jones"],# who the operator met with (not them)
  "recorded_at": "2026-05-22T14:30:00-04:00",
  "duration_minutes": 47.3,
  "speakers": ["Garrett", "John Smith"],     # voice-diarization, includes operator
  "source_file_id": "rec_abc123",
  "transcript_excerpt": "...first 500 chars...",   # used for the routing audit
  "action_items": [ {action, owner, due, priority, context, source_timestamp}, ... ],
  "decisions":   [ {what, why, source_timestamp}, ... ],
  "open_questions": [ {question, raised_by, source_timestamp}, ... ],
  "notable_quotes": [ {quote, speaker, source_timestamp}, ... ]
}

Filename collision policy: if the target filename already exists (same
prefix + title + attendees on a different day), the recorded date is
appended: 'KP.Q3 Plans (John Smith) - 2026-05-22.docx'. If THAT exists
too (two meetings same day with the same title + attendees), append the
HHMM as well: 'KP.Q3 Plans (John Smith) - 2026-05-22 1430.docx'.

Usage:
    python3 docx_writer.py --input /tmp/meeting.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

CONFIG_PATH = Path.home() / ".claude" / "skills" / "meetings-digest" / "config.json"

try:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
except ImportError:
    sys.stderr.write("ERROR: python-docx not installed. Run: python3 -m pip install python-docx\n")
    sys.exit(1)


def load_config() -> dict[str, Any]:
    if not CONFIG_PATH.exists():
        sys.stderr.write(f"ERROR: config not found at {CONFIG_PATH}\n")
        sys.exit(1)
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def sanitize_filename(s: str, max_len: int = 80) -> str:
    """Make a string safe for Windows + Mac filesystems."""
    s = re.sub(r'[\\/:*?"<>|]', "", s)        # forbidden chars
    s = re.sub(r"\s+", " ", s).strip()        # collapse whitespace
    if len(s) > max_len:
        s = s[:max_len].rstrip()
    return s or "untitled"


def resolve_recording_datetime(recorded_at_iso: str | None) -> datetime:
    if not recorded_at_iso:
        return datetime.now()
    try:
        # tolerate trailing Z
        return datetime.fromisoformat(recorded_at_iso.replace("Z", "+00:00"))
    except ValueError:
        return datetime.now()


def write_docx(meeting: dict[str, Any], output_path: Path) -> None:
    doc = Document()

    # ---- Heading ----
    h = doc.add_heading(meeting.get("recording_title") or "Untitled Meeting", level=1)

    # ---- Meta line ----
    recorded = resolve_recording_datetime(meeting.get("recorded_at"))
    duration = meeting.get("duration_minutes")
    speakers = meeting.get("speakers") or []
    attendees = meeting.get("attendees") or []
    mtype = meeting.get("meeting_type") or "Uncategorized"

    meta = doc.add_paragraph()
    meta_runs = [
        ("Date: ", True),
        (recorded.strftime("%A, %B %d, %Y at %I:%M %p"), False),
    ]
    if duration:
        meta_runs += [("\nDuration: ", True), (f"{int(duration)} min", False)]
    if attendees:
        meta_runs += [("\nAttendees: ", True), (", ".join(attendees), False)]
    if speakers:
        meta_runs += [("\nSpeakers (detected): ", True), (", ".join(speakers), False)]
    meta_runs += [("\nMeeting type: ", True), (mtype, False)]
    for text, bold in meta_runs:
        r = meta.add_run(text)
        r.bold = bold
        r.font.size = Pt(10)

    doc.add_paragraph()  # spacing

    # ---- Action items (☐ prefix so it visually reads as a checklist) ----
    doc.add_heading("Action items", level=2)
    items = meeting.get("action_items") or []
    if items:
        for item in items:
            p = doc.add_paragraph(style="List Bullet")
            box = p.add_run("☐ ")
            box.font.size = Pt(11)
            r = p.add_run(item.get("action", "(no text)"))
            r.bold = True
            # Owner / due / priority on second line
            details = []
            if item.get("owner"):
                details.append(f"Owner: {item['owner']}")
            if item.get("due"):
                details.append(f"Due: {item['due']}")
            if item.get("priority"):
                details.append(f"Priority: {item['priority']}")
            if item.get("context"):
                details.append(f"Context: {item['context']}")
            if item.get("source_timestamp"):
                details.append(f"@ {item['source_timestamp']}")
            if details:
                sub = doc.add_paragraph()
                sub.paragraph_format.left_indent = Inches(0.5)
                sub.paragraph_format.space_before = Pt(0)
                sr = sub.add_run("   " + " · ".join(details))
                sr.italic = True
                sr.font.size = Pt(9)
                sr.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
    else:
        doc.add_paragraph("(no action items extracted)")

    # ---- Decisions ----
    doc.add_heading("Decisions made", level=2)
    decisions = meeting.get("decisions") or []
    if decisions:
        for d in decisions:
            p = doc.add_paragraph(style="List Bullet")
            r = p.add_run(d.get("what", "(no text)"))
            r.bold = True
            if d.get("why"):
                p.add_run(f" — {d['why']}")
            if d.get("source_timestamp"):
                ts = doc.add_paragraph()
                ts.paragraph_format.left_indent = Inches(0.5)
                ts.paragraph_format.space_before = Pt(0)
                ts_run = ts.add_run(f"   @ {d['source_timestamp']}")
                ts_run.italic = True
                ts_run.font.size = Pt(9)
                ts_run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
    else:
        doc.add_paragraph("(none)")

    # ---- Open questions ----
    doc.add_heading("Open questions", level=2)
    questions = meeting.get("open_questions") or []
    if questions:
        for q in questions:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(q.get("question", "(no text)"))
            if q.get("raised_by"):
                p.add_run(f"  — raised by {q['raised_by']}")
            if q.get("source_timestamp"):
                p.add_run(f"  @ {q['source_timestamp']}")
    else:
        doc.add_paragraph("(none)")

    # ---- Notable quotes ----
    quotes = meeting.get("notable_quotes") or []
    if quotes:
        doc.add_heading("Notable quotes", level=2)
        for q in quotes:
            p = doc.add_paragraph(style="Intense Quote")
            r = p.add_run(q.get("quote", "(no text)"))
            attribution_bits = []
            if q.get("speaker"):
                attribution_bits.append(q["speaker"])
            if q.get("source_timestamp"):
                attribution_bits.append(q["source_timestamp"])
            if attribution_bits:
                attrib = doc.add_paragraph()
                attrib.paragraph_format.left_indent = Inches(0.5)
                ar = attrib.add_run(" — " + " @ ".join(attribution_bits))
                ar.italic = True
                ar.font.size = Pt(9)

    # ---- Footer ----
    doc.add_paragraph()
    f = doc.add_paragraph()
    fr = f.add_run(
        f"Generated by Plaud Meetings Digest on {datetime.now().strftime('%Y-%m-%d %H:%M')}.  "
        f"Recording ID: {meeting.get('source_file_id', '?')}"
    )
    fr.italic = True
    fr.font.size = Pt(8)
    fr.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    # ---- Save ----
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))


def resolve_routing_entry(meeting_type: str, config: dict[str, Any]) -> dict[str, Any]:
    """Return the matching meeting_routing.types entry for a meeting_type, or
    a synthetic fallback entry if it's the Uncategorized folder."""
    routing = config.get("meeting_routing", {})
    for entry in routing.get("types", []):
        if entry.get("folder") == meeting_type:
            return entry
    fallback_folder = routing.get("fallback_folder") or "Uncategorized"
    if meeting_type == fallback_folder:
        return {
            "folder": fallback_folder,
            "filename_prefix": routing.get("fallback_filename_prefix", "") or "",
            "rollup_filename_prefix": None,
            "weekly_subfolders": False,
            "include_in_weekly_rollup": False,
        }
    return {}


def week_folder_name(recorded: datetime, prefix: str) -> str:
    """
    Build a per-week subfolder name from a recording date.

    Format: '{prefix}.{Month} {start_day}-{end_day}, {year} (Week {iso_week})'
    Mon-Fri range labeling (workweek convention) — but the ISO week
    semantically covers Mon-Sun, so weekend recordings still bucket here.

    Examples:
      week_folder_name(2026-05-27, 'KPM') → 'KPM.May 25-29, 2026 (Week 22)'
      week_folder_name(2026-05-30, 'KPM') → 'KPM.May 25-29, 2026 (Week 22)'  (Sat → same bucket)
      week_folder_name(2026-06-01, 'KPM') → 'KPM.Jun 1-5, 2026 (Week 23)'
      week_folder_name(2026-05-29, 'KPM') with cross-month week:
        Mon May 25 - Fri May 29 → 'KPM.May 25-29, 2026 (Week 22)'
      A genuine cross-month week (e.g. recording on Mon Jun 1, week is May 28 to Jun 3):
        → 'KPM.Jun 1-5, 2026 (Week 23)'  (current week, no cross-month)
      For a week that genuinely spans months (e.g. Mon Mar 30 to Fri Apr 3):
        → 'KPM.Mar 30-Apr 3, 2026 (Week 14)'
    """
    iso_year, iso_week, iso_weekday = recorded.isocalendar()
    # iso_weekday: Mon=1, Sun=7
    monday = recorded - timedelta(days=iso_weekday - 1)
    friday = monday + timedelta(days=4)

    if monday.month == friday.month:
        date_range = f"{monday.strftime('%b')} {monday.day}-{friday.day}, {monday.year}"
    else:
        date_range = f"{monday.strftime('%b')} {monday.day}-{friday.strftime('%b')} {friday.day}, {monday.year}"

    if prefix:
        return f"{prefix}.{date_range} (Week {iso_week})"
    return f"{date_range} (Week {iso_week})"


def resolve_filename_prefix(meeting_type: str, config: dict[str, Any]) -> str:
    """
    Look up filename_prefix from config.meeting_routing.types matching the
    routed meeting_type. Falls back to fallback_filename_prefix (default "UN")
    for the Uncategorized folder. Returns empty string if config has no
    prefix info at all (defensive — older installs pre-v2.2.1 may not have
    the field; in that case fall back to the bare title).
    """
    routing = config.get("meeting_routing", {})
    for entry in routing.get("types", []):
        if entry.get("folder") == meeting_type:
            return entry.get("filename_prefix", "") or ""
    fallback_folder = routing.get("fallback_folder") or "Uncategorized"
    if meeting_type == fallback_folder:
        return routing.get("fallback_filename_prefix", "") or ""
    return ""


def resolve_output_path(meeting: dict[str, Any], base_dir: Path, config: dict[str, Any]) -> Path:
    """
    Compute the .docx output path under base_dir / 'Plaud Meetings' / <meeting_type>.

    Filename format (v2.2.1+): '{prefix}.{title} ({attendees}).docx'
      e.g. 'KP.Q3 Plans (John Smith, Sarah Jones).docx'

    Collision handling: if the target filename already exists, append the
    recorded date — and if THAT exists, append HHMM as well.
    """
    recorded = resolve_recording_datetime(meeting.get("recorded_at"))
    mtype = meeting.get("meeting_type") or "Uncategorized"
    title = meeting.get("recording_title") or "Untitled"
    attendees = meeting.get("attendees") or []
    entry = resolve_routing_entry(mtype, config)
    prefix = entry.get("filename_prefix", "") or ""
    weekly_subfolders = bool(entry.get("weekly_subfolders"))

    folder = base_dir / "Plaud Meetings" / sanitize_filename(mtype, 40)
    if weekly_subfolders:
        # Insert a per-week subfolder. Use the same prefix as the meeting
        # files (e.g. KPM) so a folder listing reads as a coherent set:
        #   KPM.May 25-29, 2026 (Week 22)/
        #     KPM.Q3 Plans (John Smith).docx
        folder = folder / sanitize_filename(week_folder_name(recorded, prefix), 90)

    # Build base filename: '{prefix}.{title}' or just '{title}' if no prefix
    title_part = sanitize_filename(title, 60)
    if prefix:
        base = f"{prefix}.{title_part}"
    else:
        base = title_part

    # Attendees: cap at 3 to keep filename under Windows 260-char path ceiling
    if attendees:
        attendee_strs = [sanitize_filename(a, 25) for a in attendees if a]
        attendee_strs = [a for a in attendee_strs if a]
        if len(attendee_strs) > 3:
            attendee_strs = attendee_strs[:3] + [f"+{len(attendees) - 3} more"]
        if attendee_strs:
            base = f"{base} ({', '.join(attendee_strs)})"

    candidate = folder / f"{base}.docx"
    if not candidate.exists():
        return candidate

    # Collision: append date
    date_part = recorded.strftime("%Y-%m-%d")
    candidate = folder / f"{base} - {date_part}.docx"
    if not candidate.exists():
        return candidate

    # Same-day collision: append HHMM too
    time_part = recorded.strftime("%Y-%m-%d %H%M")
    return folder / f"{base} - {time_part}.docx"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to JSON file with meeting data")
    parser.add_argument("--output", help="Explicit output path (overrides config-based routing)")
    args = parser.parse_args()

    config = load_config()
    base_dir_str = config.get("destination", {}).get("onedrive_folder")
    if not base_dir_str:
        sys.stderr.write("ERROR: destination.onedrive_folder not configured. Re-run install.\n")
        return 1

    base_dir = Path(base_dir_str).expanduser()
    if not base_dir.exists():
        sys.stderr.write(f"WARNING: OneDrive folder doesn't exist at {base_dir}; creating.\n")
        base_dir.mkdir(parents=True, exist_ok=True)

    in_path = Path(args.input)
    if not in_path.exists():
        sys.stderr.write(f"ERROR: input JSON missing: {in_path}\n")
        return 1
    meeting = json.loads(in_path.read_text(encoding="utf-8"))

    out_path = Path(args.output) if args.output else resolve_output_path(meeting, base_dir, config)
    write_docx(meeting, out_path)

    print(str(out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
